//decks array at bottom
export const FoodAndCooking1 = [
  //Verified
  { front: "apple", back: "manzana" },
  { front: "banana", back: "plátano" },
  { front: "grapes", back: "uvas" },
  { front: "lemon", back: "limón" },
  { front: "orange", back: "naranja" },
  { front: "strawberry", back: "fresa" },
  { front: "watermelon", back: "sandía" },
  { front: "pineapple", back: "piña" },
  { front: "blueberry", back: "arándano" },
  { front: "cherry", back: "cereza" },
  { front: "bread", back: "pan" },
  { front: "butter", back: "mantequilla" },
  { front: "cheese", back: "queso" },
  { front: "egg", back: "huevo" },
  { front: "meat", back: "carne" },
  { front: "fish", back: "pescado" },
  { front: "chicken", back: "pollo" },
  { front: "vegetables", back: "vegetales" },
  { front: "rice", back: "arroz" },
  { front: "potato", back: "papa" },
  { front: "salt", back: "sal" },
  { front: "sugar", back: "azúcar" },
  { front: "pepper", back: "pimienta" },
  { front: "oil", back: "aceite" },
  { front: "milk", back: "leche" },
  { front: "water", back: "agua" },
  { front: "coffee", back: "café" },
  { front: "tea", back: "té" },
  { front: "juice", back: "jugo" },
  { front: "soup", back: "sopa" },
  { front: "salad", back: "ensalada" },
  { front: "pasta", back: "pasta" },
  { front: "sauce", back: "salsa" },
  { front: "bowl", back: "tazón" },
  { front: "plate", back: "plato" },
  { front: "fork", back: "tenedor" },
  { front: "knife", back: "cuchillo" },
  { front: "spoon", back: "cuchara" },
  { front: "glass", back: "vaso" },
  { front: "bottle", back: "botella" },
  { front: "cup", back: "taza" },
  { front: "breakfast", back: "desayuno" },
  { front: "lunch", back: "almuerzo" },
  { front: "dinner", back: "cena" },
  { front: "snack", back: "merienda" },
  { front: "cook", back: "cocinar" },
  { front: "eat", back: "comer" },
  { front: "drink", back: "beber" },
  { front: "taste", back: "sabor" },
  { front: "spicy", back: "picante" },
  { front: "sweet", back: "dulce" },
  { front: "sour", back: "agrio" },
  { front: "bitter", back: "amargo" },
  { front: "hot", back: "caliente" },
  { front: "cold", back: "frío" },
  { front: "delicious", back: "delicioso" },
  { front: "hungry", back: "hambriento" },
  { front: "full", back: "lleno" },
  { front: "kitchen", back: "cocina" },
  { front: "restaurant", back: "restaurante" },
  { front: "menu", back: "menú" },
  { front: "waiter", back: "camarero" },
  { front: "chef", back: "chef" },
  { front: "bake", back: "hornear" },
  { front: "boil", back: "hervir" },
  { front: "fry", back: "freír" },
  { front: "grill", back: "asar" },
  { front: "stir", back: "revolver" },
  { front: "chop", back: "picar" },
  { front: "mix", back: "mezclar" },
  { front: "peel", back: "pelar" },
  { front: "cut", back: "cortar" },
  { front: "recipe", back: "receta" },
  { front: "ingredients", back: "ingredientes" },
  { front: "seasoning", back: "condimento" },
];

let FoodAndCooking3 = [
  //Verified
  { front: "artichoke", back: "alcachofa" },
  { front: "asparagus", back: "espárrago" },
  { front: "broccoli", back: "brócoli" },
  { front: "cauliflower", back: "coliflor" },
  { front: "cabbage", back: "repollo" },
  { front: "celery", back: "apio" },
  { front: "spinach", back: "espinacas" },
  { front: "zucchini", back: "calabacín" },
  { front: "peach", back: "melocotón" },
  { front: "raspberry", back: "frambuesa" },
  { front: "pomegranate", back: "granada" },
  { front: "apricot", back: "albaricoque" },
  { front: "fig", back: "higo" },
  { front: "quince", back: "membrillo" },
  { front: "turkey", back: "pavo" },
  { front: "venison", back: "venado" },
  { front: "duck", back: "pato" },
  { front: "veal", back: "ternera" },
  { front: "lamb", back: "cordero" },
  { front: "lobster", back: "langosta" },
  { front: "mussels", back: "mejillones" },
  { front: "shrimp", back: "gamba" },
  { front: "squid", back: "calamar" },
  { front: "octopus", back: "pulpo" },
  { front: "clams", back: "almejas" },
  { front: "caviar", back: "caviar" },
  { front: "sausage", back: "salchicha" },
  { front: "chorizo", back: "chorizo" },
  { front: "paella", back: "paella" },
  { front: "tapas", back: "tapas" },
  { front: "cuisine", back: "cocina" },
  { front: "gourmet", back: "gourmet" },
  { front: "appetizer", back: "aperitivo" },
  { front: "main course", back: "plato principal" },
  { front: "dessert", back: "postre" },
  { front: "beverage", back: "bebida" },
  { front: "digestif", back: "digestivo" },
  { front: "herbs", back: "hierbas" },
  { front: "spices", back: "especias" },
  { front: "vinegar", back: "vinagre" },
  { front: "ferment", back: "fermentar" },
  { front: "preserve", back: "preservar" },
  { front: "dehydrate", back: "deshidratar" },
  { front: "marinate", back: "marinar" },
  { front: "saute", back: "saltear" },
  { front: "roast", back: "asar" },
  { front: "blanch", back: "blanquear" },
  { front: "steep", back: "infundir" },
  { front: "simmer", back: "hervir a fuego lento" },
  { front: "whisk", back: "batir" },
  { front: "knead", back: "amasar" },
  { front: "fermentation", back: "fermentación" },
  { front: "caramelization", back: "caramelización" },
  { front: "braise", back: "brasear" },
  { front: "broil", back: "gratinar" },
  { front: "barbecue", back: "barbacoa" },
  { front: "poach", back: "escalfar" },
  { front: "garnish", back: "guarnición" },
  { front: "cuisine", back: "gastronomía" },
  { front: "connoisseur", back: "conocedor" },
  { front: "charcuterie", back: "charcutería" },
  { front: "sourdough", back: "masa madre" },
  { front: "baguette", back: "baguette" },
  { front: "crouton", back: "costrón" },
  { front: "croissant", back: "croissant" },
  { front: "macaron", back: "macarón" },
];

let FoodAndCooking2 = [
  { front: "pork", back: "cerdo" },
  { front: "bacon", back: "tocino" },
  { front: "ham", back: "jamón" },
  { front: "sausage", back: "salchicha" },
  { front: "ribs", back: "costillas" },
  { front: "pork chop", back: "chuleta de cerdo" },
  { front: "pork belly", back: "panceta" },
  { front: "pork loin", back: "lomo de cerdo" },
  { front: "pork shoulder", back: "paleta de cerdo" },
  { front: "prosciutto", back: "prosciutto" },
  { front: "chorizo", back: "chorizo" },
  { front: "salami", back: "salami" },
  { front: "pepperoni", back: "pepperoni" },
  { front: "pulled pork", back: "cerdo desmenuzado" },
  { front: "carnitas", back: "carnitas" },
  { front: "suckling pig", back: "cochinillo" },
  { front: "pork and beans", back: "cerdo con frijoles" },
  { front: "wiener schnitzel", back: "wiener schnitzel" },
  { front: "pigs in a blanket", back: "salchichas en camisa" },
  { front: "pork rinds", back: "chicharrones" },
  { front: "blood sausage", back: "morcilla" },
  { front: "head cheese", back: "queso de cabeza" },
  { front: "spam", back: "spam" },
  { front: "pork pie", back: "pastel de cerdo" },
  { front: "beef", back: "carne de res" },
  { front: "steak", back: "bistec" },
  { front: "hamburger", back: "hamburguesa" },
  { front: "meatball", back: "albóndiga" },
  { front: "ribs", back: "costillas" },
  { front: "roast beef", back: "rostbif, carne asada" },
  { front: "beef stew", back: "estofado de carne" },
  { front: "beef jerky", back: "carne seca" },
  { front: "brisket", back: "pecho" },
  { front: "t-bone steak", back: "bistec t-bone" },
  { front: "filet mignon", back: "filete mignon" },
  { front: "sirloin", back: "solomillo" },
  { front: "rump", back: "rabadilla" },
  { front: "beef tartare", back: "tartar de carne" },
  { front: "corned beef", back: "carne en conserva" },
  { front: "ground beef", back: "carne molida" },
  { front: "prime rib", back: "costilla prima" },
  { front: "beef wellington", back: "wellington de carne" },
  { front: "carpaccio", back: "carpaccio" },
  { front: "bulgogi", back: "bulgogi" },
  { front: "pot roast", back: "asado de olla" },
  { front: "short ribs", back: "costillas cortas" },
  { front: "chuck", back: "aguja" },
  { front: "osso buco", back: "osso buco" },
  { front: "beef bourguignon", back: "boeuf bourguignon" },

  { front: "shank", back: "jarrete" },
  { front: "flank", back: "falda" },
  { front: "beef stock", back: "caldo de carne" },
  { front: "fish", back: "pescado" },
  { front: "salmon", back: "salmón" },
  { front: "tuna", back: "atún" },
  { front: "cod", back: "bacalao" },
  { front: "trout", back: "trucha" },
  { front: "sardine", back: "sardina" },
  { front: "mackerel", back: "caballa" },
  { front: "herring", back: "arenque" },
  { front: "anchovy", back: "anchoa" },
  { front: "fish and chips", back: "pescado con papas fritas" },
  { front: "ceviche", back: "ceviche" },
  { front: "fish soup", back: "sopa de pescado" },
  { front: "grilled fish", back: "pescado a la parrilla" },
  { front: "fried fish", back: "pescado frito" },
  { front: "fish stew", back: "guiso de pescado" },
  { front: "fish cake", back: "pastel de pescado" },
  { front: "fish pie", back: "pastel de pescado" },
  { front: "smoked fish", back: "pescado ahumado" },
  { front: "pickled fish", back: "pescado en escabeche" },
  { front: "sushi", back: "sushi" },
  { front: "sashimi", back: "sashimi" },
  { front: "clam chowder", back: "sopa de almejas" },
  { front: "lobster bisque", back: "sopa de langosta" },
  { front: "paella", back: "paella" },
  { front: "tempura", back: "tempura" },
  { front: "caviar", back: "caviar" },
  { front: "escargot", back: "caracol" },
  { front: "calamari", back: "calamar" },
  { front: "prawns", back: "langostinos" },
  { front: "fish stock", back: "caldo de pescado" },
];

let FoodAndCooking4 = [
  { front: "shellfish", back: "mariscos" },
  { front: "shrimp", back: "camarón" },
  { front: "lobster", back: "langosta" },
  { front: "crab", back: "cangrejo" },
  { front: "oyster", back: "ostra" },
  { front: "clam", back: "almeja" },
  { front: "mussel", back: "mejillón" },
  { front: "scallop", back: "vieira" },
  { front: "squid", back: "calamar" },
  { front: "octopus", back: "pulpo" },
  { front: "prawn", back: "gamba" },
  { front: "caviar", back: "caviar" },
  { front: "sea urchin", back: "erizo de mar" },
  { front: "lobster bisque", back: "bisque de langosta" },
  { front: "paella", back: "paella" },
  { front: "chicken", back: "pollo" },
  { front: "chicken wings", back: "alitas de pollo" },
  { front: "chicken breast", back: "pechuga de pollo" },
  { front: "chicken thigh", back: "muslo de pollo" },
  { front: "chicken drumstick", back: "pata de pollo" },
  { front: "chicken nuggets", back: "nuggets de pollo" },
  { front: "chicken soup", back: "sopa de pollo" },
  { front: "chicken salad", back: "ensalada de pollo" },
  { front: "fried chicken", back: "pollo frito" },
  { front: "grilled chicken", back: "pollo a la parrilla" },
  { front: "roast chicken", back: "pollo asado" },
  { front: "chicken curry", back: "curry de pollo" },
  { front: "chicken stir fry", back: "salteado de pollo" },
  { front: "chicken pot pie", back: "pastel de pollo" },
  { front: "chicken and rice", back: "pollo con arroz" },
  { front: "chicken teriyaki", back: "teriyaki de pollo" },
  { front: "chicken parmigiana", back: "parmigiana de pollo" },
  { front: "chicken alfredo", back: "alfredo de pollo" },
  { front: "chicken cacciatore", back: "pollo a la cazadora" },
  { front: "chicken marsala", back: "pollo marsala" },
  { front: "chicken piccata", back: "pollo piccata" },
  { front: "chicken tikka masala", back: "pollo tikka masala" },
  { front: "chicken katsu", back: "katsu de pollo" },
  { front: "chicken shawarma", back: "shawarma de pollo" },
  { front: "chicken enchiladas", back: "enchiladas de pollo" },
  { front: "chicken quesadilla", back: "quesadilla de pollo" },
  { front: "chicken gumbo", back: "gumbo de pollo" },
  { front: "chicken souvlaki", back: "souvlaki de pollo" },
  { front: "chicken tagine", back: "tagine de pollo" },
  { front: "chicken stock", back: "caldo de pollo" },
  { front: "grilled fish", back: "pescado a la parrilla" },
  { front: "fried fish", back: "pescado frito" },
  { front: "steamed fish", back: "pescado al vapor" },
  { front: "baked fish", back: "pescado al horno" },
  { front: "poached fish", back: "pescado pochado" },
  { front: "smoked fish", back: "pescado ahumado" },
  { front: "pickled fish", back: "pescado en escabeche" },
  { front: "raw fish", back: "pescado crudo" },
  { front: "fish soup", back: "sopa de pescado" },
  { front: "fish stew", back: "guiso de pescado" },
  { front: "fish curry", back: "curry de pescado" },
  { front: "fish and chips", back: "pescado con papas fritas" },
  { front: "fish tacos", back: "tacos de pescado" },
  { front: "fish sandwich", back: "sándwich de pescado" },
  { front: "fish pie", back: "pastel de pescado" },
];

let advancedFoodAndCooking = [
  // Fish
  { front: "fish roe", back: "huevas de pescado" },
  { front: "fish head", back: "cabeza de pescado" },
  { front: "fish skin", back: "piel de pescado" },
  { front: "fish fins", back: "aletas de pescado" },
  { front: "fish gills", back: "branquias de pescado" },

  // Pig
  { front: "pig trotters", back: "patas de cerdo" },
  { front: "pig tail", back: "cola de cerdo" },
  { front: "pig ears", back: "orejas de cerdo" },
  { front: "pig snout", back: "hocico de cerdo" },
  { front: "pig liver", back: "hígado de cerdo" },

  // Beef
  { front: "oxtail", back: "rabia de buey" },
  { front: "beef tongue", back: "lengua de vaca" },
  { front: "beef tripe", back: "callos de ternera" },
  { front: "beef liver", back: "hígado de ternera" },
  { front: "beef heart", back: "corazón de vaca" },

  // Chicken
  { front: "chicken gizzard", back: "molleja de pollo" },
  { front: "chicken heart", back: "corazón de pollo" },
  { front: "chicken liver", back: "hígado de pollo" },
  { front: "chicken feet", back: "patas de pollo" },
  { front: "chicken head", back: "cabeza de pollo" },

  // More for each
  { front: "fish liver", back: "hígado de pescado" },
  { front: "pig kidney", back: "riñón de cerdo" },
  { front: "beef kidney", back: "riñón de vaca" },
  { front: "chicken neck", back: "cuello de pollo" },
  { front: "fish intestines", back: "intestinos de pescado" },
  { front: "pig spleen", back: "bazo de cerdo" },
  { front: "beef brain", back: "cerebro de vaca" },
  { front: "chicken comb", back: "cresta de pollo" },
  { front: "fish tail", back: "cola de pescado" },
  { front: "pig testicles", back: "testículos de cerdo" },
];

export const presetDecks = [
  { name: "Food and Cooking 1", cards: FoodAndCooking1 },
  { name: "Food and Cooking 2", cards: FoodAndCooking2 },
  { name: "Food and Cooking 3", cards: FoodAndCooking3 },
  { name: "Food and Cooking 4", cards: FoodAndCooking4 },
  { name: "Advanced Food and Cooking", cards: advancedFoodAndCooking },
];
