const beginnerLatinAmericanFoodVocabulary = [
  { front: "apple", back: "manzana" },
  { front: "banana", back: "banana" },
  { front: "orange", back: "naranja" },
  { front: "rice", back: "arroz" },
  { front: "beans", back: "frijoles" },
  { front: "chicken", back: "pollo" },
  { front: "beef", back: "carne de res" },
  { front: "fish", back: "pescado" },
  { front: "lettuce", back: "lechuga" },
  { front: "tomato", back: "tomate" },
  { front: "onion", back: "cebolla" },
  { front: "garlic", back: "ajo" },
  { front: "pepper", back: "pimiento" },
  { front: "potato", back: "papa" },
  { front: "carrot", back: "zanahoria" },
  { front: "corn", back: "maíz" },
  { front: "sugar", back: "azúcar" },
  { front: "salt", back: "sal" },
  { front: "oil", back: "aceite" },
  { front: "bread", back: "pan" },
];

const beginnerLatinAmericanFoodVocabulary2 = [
  { front: "cheese", back: "queso" },
  { front: "butter", back: "mantequilla" },
  { front: "egg", back: "huevo" },
  { front: "milk", back: "leche" },
  { front: "meat", back: "carne" },
  { front: "pork", back: "cerdo" },
  { front: "sausage", back: "salchicha" },
  { front: "soup", back: "sopa" },
  { front: "salad", back: "ensalada" },
  { front: "dessert", back: "postre" },
  { front: "coffee", back: "café" },
  { front: "tea", back: "té" },
  { front: "juice", back: "jugo" },
  { front: "water", back: "agua" },
  { front: "wine", back: "vino" },
  { front: "beer", back: "cerveza" },
  { front: "soda", back: "refresco" },
  { front: "fruit", back: "fruta" },
  { front: "vegetable", back: "vegetal" },
  { front: "meal", back: "comida" },
];

const beginnerLatinAmericanFoodVocabulary3 = [
  { front: "breakfast", back: "desayuno" },
  { front: "lunch", back: "almuerzo" },
  { front: "dinner", back: "cena" },
  { front: "snack", back: "merienda" },
  { front: "hamburger", back: "hamburguesa" },
  { front: "pizza", back: "pizza" },
  { front: "sandwich", back: "sándwich" },
  { front: "pasta", back: "pasta" },
  { front: "rice", back: "arroz" },
  { front: "chocolate", back: "chocolate" },
  { front: "cake", back: "pastel" },
  { front: "cookie", back: "galleta" },
  { front: "ice cream", back: "helado" },
  { front: "honey", back: "miel" },
  { front: "jam", back: "mermelada" },
  { front: "peanut", back: "cacahuate" },
  { front: "almond", back: "almendra" },
  { front: "peach", back: "durazno" },
  { front: "strawberry", back: "fresa" },
  { front: "cherry", back: "cereza" },
];

const beginnerLatinAmericanFoodVocabulary4 = [
  { front: "turkey", back: "pavo" },
  { front: "duck", back: "pato" },
  { front: "lamb", back: "cordero" },
  { front: "bacon", back: "tocino" },
  { front: "shrimp", back: "camarón" },
  { front: "lobster", back: "langosta" },
  { front: "crab", back: "cangrejo" },
  { front: "salmon", back: "salmón" },
  { front: "tuna", back: "atún" },
  { front: "mushroom", back: "hongo" },
  { front: "cucumber", back: "pepino" },
  { front: "spinach", back: "espinaca" },
  { front: "broccoli", back: "brócoli" },
  { front: "celery", back: "apio" },
  { front: "grape", back: "uva" },
  { front: "melon", back: "melón" },
  { front: "coconut", back: "coco" },
  { front: "pineapple", back: "piña" },
  { front: "mango", back: "mango" },
  { front: "avocado", back: "aguacate" },
];

const beginnerLatinAmericanFoodVocabulary5 = [
  { front: "kiwi", back: "kiwi" },
  { front: "raspberry", back: "frambuesa" },
  { front: "blueberry", back: "arándano" },
  { front: "blackberry", back: "mora" },
  { front: "pear", back: "pera" },
  { front: "plum", back: "ciruela" },
  { front: "grapefruit", back: "pomelo" },
  { front: "lime", back: "lima" },
  { front: "lemon", back: "limón" },
  { front: "pomegranate", back: "granada" },
  { front: "fig", back: "higo" },
  { front: "apricot", back: "albaricoque" },
  { front: "guava", back: "guayaba" },
  { front: "papaya", back: "papaya" },
  { front: "date", back: "dátil" },
  { front: "kiwi", back: "kiwi" },
  { front: "raspberry", back: "frambuesa" },
  { front: "peanut butter", back: "crema de cacahuate" },
  { front: "olive", back: "aceituna" },
  { front: "pickle", back: "pepinillo" },
];

const beginnerLatinAmericanFoodVocabulary6 = [
  { front: "zucchini", back: "calabacín" },
  { front: "cauliflower", back: "coliflor" },
  { front: "artichoke", back: "alcachofa" },
  { front: "asparagus", back: "espárragos" },
  { front: "eggplant", back: "berenjena" },
  { front: "pumpkin", back: "calabaza" },
  { front: "radish", back: "rábano" },
  { front: "cabbage", back: "col" },
  { front: "beetroot", back: "remolacha" },
  { front: "pea", back: "guisante" },
  { front: "turnip", back: "nabo" },
  { front: "leek", back: "puerro" },
  { front: "shallot", back: "chalote" },
  { front: "brussels sprouts", back: "coles de Bruselas" },
  { front: "chili", back: "chile" },
  { front: "okra", back: "quimbombó" },
  { front: "squash", back: "calabacín" },
  { front: "parsnip", back: "pastinaca" },
  { front: "yam", back: "ñame" },
  { front: "sweet potato", back: "batata" },
];

const beginnerLatinAmericanFoodVocabulary7 = [
  { front: "ketchup", back: "ketchup" },
  { front: "mustard", back: "mostaza" },
  { front: "mayonnaise", back: "mayonesa" },
  { front: "vinegar", back: "vinagre" },
  { front: "soy sauce", back: "salsa de soya" },
  { front: "hot sauce", back: "salsa picante" },
  { front: "barbecue sauce", back: "salsa barbacoa" },
  { front: "wheat", back: "trigo" },
  { front: "oat", back: "avena" },
  { front: "rye", back: "centeno" },
  { front: "barley", back: "cebada" },
  { front: "flour", back: "harina" },
  { front: "yeast", back: "levadura" },
  { front: "syrup", back: "jarabe" },
  { front: "hazelnut", back: "avellana" },
  { front: "walnut", back: "nuez" },
  { front: "chestnut", back: "castaña" },
  { front: "pecan", back: "nuez de pecán" },
  { front: "cashew", back: "anacardo" },
  { front: "pistachio", back: "pistacho" },
];

const beginnerLatinAmericanFoodVocabulary8 = [
  { front: "macaroni", back: "macarrones" },
  { front: "spaghetti", back: "espaguetis" },
  { front: "lasagna", back: "lasaña" },
  { front: "ravioli", back: "raviolis" },
  { front: "noodle", back: "fideo" },
  { front: "pastry", back: "pastelería" },
  { front: "doughnut", back: "rosquilla" },
  { front: "muffin", back: "muffin" },
  { front: "croissant", back: "croissant" },
  { front: "baguette", back: "baguette" },
  { front: "pancake", back: "panqueque" },
  { front: "waffle", back: "gofre" },
  { front: "toast", back: "tostada" },
  { front: "biscuit", back: "galleta" },
  { front: "brownie", back: "brownie" },
  { front: "candy", back: "caramelo" },
  { front: "lollipop", back: "piruleta" },
  { front: "marshmallow", back: "malvavisco" },
  { front: "chewing gum", back: "chicle" },
  { front: "chips", back: "papas fritas" },
];

const beginnerLatinAmericanFoodVocabulary9 = [
  { front: "salmon", back: "salmón" },
  { front: "tuna", back: "atún" },
  { front: "trout", back: "trucha" },
  { front: "mackerel", back: "caballa" },
  { front: "cod", back: "bacalao" },
  { front: "sardine", back: "sardina" },
  { front: "herring", back: "arenque" },
  { front: "lobster", back: "langosta" },
  { front: "crab", back: "cangrejo" },
  { front: "oyster", back: "ostra" },
  { front: "mussel", back: "mejillón" },
  { front: "clam", back: "almeja" },
  { front: "scallop", back: "vieira" },
  { front: "shrimp", back: "gamba" },
  { front: "octopus", back: "pulpo" },
  { front: "squid", back: "calamar" },
  { front: "jellyfish", back: "medusa" },
  { front: "seaweed", back: "algas" },
  { front: "caviar", back: "caviar" },
  { front: "prawn", back: "langostino" },
];

const beginnerLatinAmericanFoodVocabulary10 = [
  { front: "to eat", back: "comer" },
  { front: "to drink", back: "beber" },
  { front: "to cook", back: "cocinar" },
  { front: "to bake", back: "hornear" },
  { front: "to fry", back: "freír" },
  { front: "to boil", back: "hervir" },
  { front: "to grill", back: "asar" },
  { front: "to steam", back: "vapor" },
  { front: "to chop", back: "cortar" },
  { front: "to slice", back: "rebanar" },
  { front: "to peel", back: "pelar" },
  { front: "to stir", back: "revolver" },
  { front: "to mix", back: "mezclar" },
  { front: "to pour", back: "verter" },
  { front: "to taste", back: "degustar" },
  { front: "to smell", back: "oler" },
  { front: "to serve", back: "servir" },
  { front: "to order", back: "ordenar" },
  { front: "to wash", back: "lavar" },
  { front: "to clean", back: "limpiar" },
];

export const beginnerFoodVocabularyDecks = {
  name: "Beginner Food",
  decks: [
    {
      name: "Beginner Food 1",
      cards: beginnerLatinAmericanFoodVocabulary,
      practiceModeScore: 0,
      activeRecallScore: 0,
    },
    {
      name: "Beginner Food 2",
      cards: beginnerLatinAmericanFoodVocabulary2,
      practiceModeScore: 0,
      activeRecallScore: 0,
    },
    {
      name: "Beginner Food 3",
      cards: beginnerLatinAmericanFoodVocabulary3,
      practiceModeScore: 0,
      activeRecallScore: 0,
    },
    {
      name: "Beginner Food 4",
      cards: beginnerLatinAmericanFoodVocabulary4,
      practiceModeScore: 0,
      activeRecallScore: 0,
    },
    {
      name: "Beginner Food 5",
      cards: beginnerLatinAmericanFoodVocabulary5,
      practiceModeScore: 0,
      activeRecallScore: 0,
    },
    {
      name: "Beginner Food 6",
      cards: beginnerLatinAmericanFoodVocabulary6,
      practiceModeScore: 0,
      activeRecallScore: 0,
    },
    {
      name: "Beginner Food 7",
      cards: beginnerLatinAmericanFoodVocabulary7,
      practiceModeScore: 0,
      activeRecallScore: 0,
    },
    {
      name: "Beginner Food 8",
      cards: beginnerLatinAmericanFoodVocabulary8,
      practiceModeScore: 0,
      activeRecallScore: 0,
    },
    {
      name: "Beginner Food 9",
      cards: beginnerLatinAmericanFoodVocabulary9,
      practiceModeScore: 0,
      activeRecallScore: 0,
    },
    {
      name: "Beginner Food 10",
      cards: beginnerLatinAmericanFoodVocabulary10,
      practiceModeScore: 0,
      activeRecallScore: 0,
    },
  ],
};

//export const presetDecks = [beginnerFoodVocabularyDecks];

export const presetFolders = [
  {
    name: "Beginner Food",
    decks: [beginnerFoodVocabularyDecks],
  },
  {},
];
